"""Add file management features with comments, permissions, and audit logs

Revision ID: aabe2f80ffb9
Revises: 63019d64b4d0
Create Date: 2025-10-26 02:45:47.730202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aabe2f80ffb9'
down_revision: Union[str, Sequence[str], None] = '63019d64b4d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('action_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['project_designs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('parent_comment_id', sa.String(), nullable=True),
    sa.Column('mentions', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['project_designs.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['file_comments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_permissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_download', sa.Boolean(), nullable=False),
    sa.Column('can_comment', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['project_designs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    with op.batch_alter_table('project_designs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.String(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('uploaded_by_id', sa.String(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('parent_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_latest_version', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('download_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.create_foreign_key('fk_project_designs_uploaded_by_id', 'users', ['uploaded_by_id'], ['id'])
        batch_op.create_foreign_key('fk_project_designs_parent_id', 'project_designs', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('project_designs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_designs_parent_id', type_='foreignkey')
        batch_op.drop_constraint('fk_project_designs_uploaded_by_id', type_='foreignkey')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('download_count')
        batch_op.drop_column('is_public')
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('is_latest_version')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('version')
        batch_op.drop_column('uploaded_by_id')
        batch_op.drop_column('file_size')
        batch_op.drop_column('file_name')
    
    op.drop_table('file_permissions')
    op.drop_table('file_comments')
    op.drop_table('file_audit_logs')
